on: workflow_dispatch
name: workflow_example
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
           pip install beautifulsoup4
           echo "-----"
           git clone https://github.com/wmgeolab/salb-input-pipeline
           echo "-----"
           cd salb-input-pipeline
           cd mentorshipWork
           echo "-----"
           pwd
           python WebScraper.py
