on: workflow_dispatch
name: workflow_example
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
           git lfs clone https://github.com/wmgeolab/salb-input-pipeline
           cd salb-input-pipeline
           python example.py
